# SPDX-FileCopyrightText: 2026 ash_r2rml contributors <https://github.com/seanchatmangpt/ash_r2rml/graphs/contributors>
#
# SPDX-License-Identifier: MIT

name: Release to Hex

on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Publish to Hex.pm
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Elixir / Erlang
        uses: erlef/setup-beam@v1
        with:
          elixir-version: '1.18.2'
          otp-version: '27.2'

      - name: Install dependencies
        run: mix deps.get

      - name: Build Hex package
        run: mix hex.build

      - name: Publish to Hex.pm
        env:
          HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
        if: env.HEX_API_KEY != ''
        run: mix hex.publish --yes
